#!/bin/sh

BLK=/dev/mmcblk0p2
SYS=/mnt/sys

# -- check parameter
if [ "$1" == "" ] || [ "$2" == "" ]; then
	echo "usage: $0 <img-name> <md5-file>"
	exit 1
fi

# -- check if MD5 file is present
if [ ! -f $2 ]; then
	echo "-> missing MD5-File ($2) ..." 
	exit 1
fi

# -- burning Image
echo -n "-> burning image $1 to $BLK ...  " 
/root/progressShow  &
PROGRESSPID=`pidof progressShow`

if df | grep -c $SYS > /dev/null; then
	test -e $SYS/boot/PPTImage.md5 && rm $SYS/boot/PPTImage.md5
	umount $SYS
fi

test -p pipe-zip || mkfifo pipe-zip
test -p pipe-md5 || mkfifo pipe-md5

dd if=$1 2> /dev/null | tee pipe-zip pipe-md5 | >/dev/null &
md5sum pipe-md5 > /tmp/burned.md5 &
gzip -c -d pipe-zip > $BLK

rm pipe-zip
rm pipe-md5
kill $PROGRESSPID

# -- check if transferred image was ok
MD5TRANSFERRED=`cat /tmp/burned.md5 2>/dev/null | cut -d " " -f 1`
MD5REFERENCE=`cat $2 2>/dev/null | cut -d " " -f 1`

if [ "$MD5TRANSFERRED" != "$MD5REFERENCE" ]; then
	echo -e "\n-> fatal: MD5-sum of file $1 isn't valid !" 
	exit 1
else
	echo " OK." 
fi

if [ $? -eq 0 ]; then
	/root/progressShow  &
	PROGRESSPID=`pidof progressShow`
	echo -n "-> mounting, resizing, labeling ...  " 
	mount $BLK $SYS
	if [ $? -ne 0 ]; then
		echo "cannot mount $BLK to $SYS !"
		exit 1
	fi
	sleep 1
	umount $SYS

	fsck.ext4 -f -p $BLK > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "fsck prior resize2fs failed!"
		exit 1
	fi

	resize2fs $BLK > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "resize2fs failed!"
		exit 1
	fi


	e2label $BLK ppt-sys
	fsck.ext4 -f -p $BLK > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "fsck failed!"
		exit 1
	fi
	kill $PROGRESSPID
	mount -a
	cp $2 $SYS/boot/PPTImage.md5
	sync
	echo " OK." 
	exit 0
else
	echo " failed!" 
	exit 1
fi

